MP3: Fix parse of the Xing header to not raise errors (#175)
## Motivation

There were some errors in our Appsignal like this:

```
undefined method `unpack' for nil:NilClass

/app/vendor/bundle/ruby/2.7.0/gems/format_parser-0.24.2/lib/parsers/mp3_parser.rb:261 attempt_xing_header
/app/vendor/bundle/ruby/2.7.0/gems/format_parser-0.24.2/lib/parsers/mp3_parser.rb:169 block in parse_mpeg_frames
/app/vendor/bundle/ruby/2.7.0/gems/format_parser-0.24.2/lib/parsers/mp3_parser.rb:141 times
/app/vendor/bundle/ruby/2.7.0/gems/format_parser-0.24.2/lib/parsers/mp3_parser.rb:141 parse_mpeg_frames
/app/vendor/bundle/ruby/2.7.0/gems/format_parser-0.24.2/lib/parsers/mp3_parser.rb:83 call
/app/vendor/bundle/ruby/2.7.0/gems/format_parser-0.24.2/lib/format_parser.rb:203 block in 
...
```

## Problem 1 - wrong verification for the bitwise operation

We noticed that there were some wrong logics in method `attempt_xing_header` when checking the result of some bitwise operations.

For example: `puts 'true' if anything & 0` will always print `true` because `anything & 0` is equal `0` which is considered true by IF in Ruby.

So, we changed all these operations to check if the result is different than 0.

## Problem 2 - wrong unpacking for the Xing header flags

The directives used to unpack the Xing's `header_flags` were wrong.

Before:
ruby
```
# io.read(4).unpack('s>s>')
"\x00\x00\x00\x01".unpack('s>s>')
=> [0, 1]
```

After:
```ruby
# io.read(4).unpack('i>')
"\x00\x00\x00\x01".unpack('i>')
=> [1]
```

The first result would never match the bitwise operations to check if the bits are set.

We based this modification on lib Tinytag -> https://github.com/devsnd/tinytag/blob/master/tinytag/tinytag.py#L526